
spring:
  application:
    name: demo-eureka-client
  mvc:
    servlet:
      path: /custom
server:
  port: 8861
eureka:
  client:
    service-url:
      defaultZone: http://maikec:123@localhost:8761/eureka/
  instance:
    status-page-url: ${spring.mvc.servlet.path}/info
    health-check-url-path: ${spring.mvc.servlet.path}/health
