
spring:
  application:
    name: demo-eureka-server
  security:
    user:
      name: maikec
      password: 123

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defualtZon: http://${eureka.instance.hostname}:${server.port}/eureka/